config/routes.rb
TazkasPollster::Application.routes.draw do
  resources :polls, :only => [:index, :new, :create, :destroy]
  resources :questions
  resources :choices

  get     'polls/edit/:edit_key(.:format)'            =>  'polls#edit',                           :as => :poll_edit
  get     'polls/:share_key'                          =>  "polls#show",                           :as => :poll_share
  put     'polls/update/:edit_key(.:format)'          =>  "polls#update",                         :as => :poll_update
  post    'polls/responses/:share_key(.:format)'      =>  'polls#responses',                      :as => :get_responses
  get     'polls/responses/view/:edit_key(.:format)'  =>  'polls#show_responses',                 :as => :view_responses
  get     'peanut/choices/manage/:edit_key/:question_id(.:format)' => 'questions#manage_choices', :as => :manage_choices

  root to: 'polls#index'

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :question
  attr_accessible :option, :question_id
  validates :option, :presence => true
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :name, :share_key, :edit_key
  before_create :key_gen
  has_many :questions
  accepts_nested_attributes_for :questions#, :allow_destroy => true


  private

  def key_gen
    self.edit_key = (0...4).map{65.+(rand(26)).chr}.join
    self.share_key = (0...4).map{65.+(rand(26)).chr}.join
  end


  # create a random key for editing and taking the poll
  # add two columns to the poll table to store it
  # run a before statement to get them generated
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :body, :poll_id
  belongs_to :poll
  has_many :responses
  has_many :choices
  accepts_nested_attributes_for :choices
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :question
  attr_accessible :response, :question_id

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController

  def create
    @choice = Choice.new(params[:choice])
    @choice.save
    redirect_to manage_choices_path(@choice.question.poll.edit_key, @choice.question_id)
  end
  
  
  

end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def index
    @polls = Poll.all
  end

  def new
    @poll = Poll.new
  end

  def create
    @poll = Poll.new(params[:poll])
    @poll.save
    redirect_to poll_edit_path(@poll.edit_key)
  end

  def edit
    @poll = Poll.find_by_edit_key(params[:edit_key])
    @questions = @poll.questions


    #find the poll as it comes in through the custom routes
    #find the poll via the edit key in the params
    #make sure to acco£unt for any exceptions
  end


  def update
    @poll = Poll.find_by_edit_key(params[:edit_key])
    questions = params[:poll].delete(:questions_attributes)
    @poll.update_attributes!(params[:poll])
    questions.each_value do |question|
      @question = Question.find(question[:id])
      if question.delete(:_destroy).to_i == 1
        @question.destroy
      else
        @question.update_attributes!(question)
      end
    end
    redirect_to poll_edit_path(@poll.edit_key)
  end

  def destroy
    @poll = Poll.find(params[:id])
    @poll.destroy
    redirect_to root_path
  end

  def show
    @poll = Poll.find_by_share_key(params[:share_key])
    @questions = @poll.questions
  end


  def show_responses
    @poll = Poll.find_by_edit_key(params[:edit_key])
    @questions = @poll.questions
  end


  def responses
    # @poll = Poll.find_by_share_key(params[:share_key])
    answers = params[:poll][:questions]
    answers.each do |question_id,response|
      @answer = Response.new(:response => response[:response], :question_id => question_id)
      @answer.save
    end
    redirect_to root_path
  end



















end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def create
    @question = Question.new(params[:question])
    @question.save
    redirect_to poll_edit_path(@question.poll.edit_key)
  end

  def manage_choices
    @question = Question.find(params[:question_id])
    @choices = @question.choices
  end

  def update
    @question = Question.find(params[:id])
    choices = params[:question].delete(:choices_attributes)
    # @question.update_attributes!(params[:question])
    choices.each_value do |choice|
      @choice = Choice.find(choice[:id])
       if choice.delete(:_destroy).to_i == 1
         @choice.destroy
      else
         @choice.update_attributes!(choice)
      end
    end
    redirect_to manage_choices_path(@question.poll.edit_key, @question.id)
  end
end



# multiple choices belong to a question
#questions has many choices and choices has_a qur

# poll has many questions
# poll edit page ability to add options for each question
# add edit delete options and then on our pole responses page check if question has any optioins
#if it does make radio butttons so user can choosse the options if not regular text box.
#ability to add options to a questions add a view in the same page or link to another page.

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/choices/_form.html.erb
<%= form_for Choice.new(:question_id => @question.id) do |f| %>
  <div class="field">
    <%= f.hidden_field :question_id %>
    <%= f.text_field :option %>
    <%= f.submit class: 'btn' %>
  </div>
<% end %>

app/views/choices/_update_form.html.erb
<%= form.fields_for :choices do |choices_form| %>
<table>
  <div class="field">
    <tr>
      <td><%= choices_form.text_field :option  %></td>
      <td><%= choices_form.check_box :_destroy %> delete </td>
    </tr>
  </div>

</table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TazkasPollster</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, class: 'span5' %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn' %>
  </div>
<% end %>

app/views/polls/create.html.erb
<h1>Polls#create</h1>
<p>Find me in app/views/polls/create.html.erb</p>

app/views/polls/destroy.html.erb
<h1>Polls#destroy</h1>
<p>Find me in app/views/polls/destroy.html.erb</p>

app/views/polls/edit.html.erb
<h1>Polls</h1>
<table class="table">
<p>
<tr><td>Secret Edit Poll Link:</td><td>Poll Submission Link:</td><td>Poll Responses Link:</td></tr>
<tr>
<td><%= link_to "http//localhost:3000/edit/#{@poll.edit_key}", poll_edit_path(@poll.edit_key) %></td>
<td><%= link_to "http//localhost:3000/#{@poll.share_key}", poll_share_path(@poll.share_key) %></td>
<td><%= link_to "http//localhost:3000/#{@poll.edit_key}", view_responses_path(@poll.edit_key) %></td>
</tr>
</p>
</table>

<%= form_for @poll, :url => poll_update_path(@poll.edit_key) do |poll_form| %>
<table class="table table-striped">
  <tr><td><%= poll_form.label 'Name of the Poll' %></td></tr>
  <tr><td><%= poll_form.text_field :name, class: 'span5' %></td></tr>
  <tr><td>Questions:</td><td>Remove?</td></tr>

    <%= render :partial => 'questions/update_form', :locals => {:form => poll_form}, :poll => @poll %>

  <tr>
    <td>
      <div class="actions"><%= poll_form.submit %></div>
    <td>
  </tr>

</table>
<% end %>


<p> <%= render 'questions/form', :poll => @poll %></p>

app/views/polls/index.html.erb
<table class="table table-striped">
<tr><h1>Polls</h1></tr>
<tr><td>Poll Name:</td><td></td><td></td></tr>

  <% @polls.each do |poll| %>
    <tr><td><%= poll.name %></td>
        <td><%= link_to "Edit Poll", poll_edit_path(poll.edit_key) %></td>
        <td><%= link_to "Share Poll", poll_share_path(poll.share_key) %></td>
        <td><%= link_to "Delete Poll", poll_path(poll), :method => :delete %></td>
    </tr>
  <% end %>

<tr><td><%= link_to "Create A New Poll", new_poll_path %></td></tr>
</table>

app/views/polls/new.html.erb
<h1>Polls</h1>

<%= render 'form' %>

app/views/polls/show.html.erb
<%= form_tag(get_responses_path(@poll.share_key)) do %>
<table class="table table-striped">
  <tr><h1>Take the Poll!</h1></tr>
  <tr><h2><%= @poll.name %></h2></tr>

  <% @questions.each do |question| %>
    <tr><td><%= question.body %></td></tr>
    <tr><td>
      <% if question.choices.any? %>
      <div class="radio">
        <% question.choices.each do |choice| %>
          <%= radio_button_tag("poll[questions][#{question.id}][response]", "#{choice.id}") %>
          <%= label_tag(choice.option) %>
          <% end %>
      </div>
      <% else %>

      <%= text_field_tag :response, nil, :placeholder => "Enter response", :name => "poll[questions][#{question.id}][response]" %>

      <% end %>
    </td></tr>
  <% end %>
    <tr><td><%= submit_tag("Submit Responses") %></td></tr>

</table>
<% end %>

app/views/polls/show_responses.html.erb
<table class="table">

<% @questions.each do |question| %>

  <% if question.choices.any? %>

  <tr><td><h2><%= question.body %></h2></td></tr>

    <% question.choices.each do |choice| %>

    <tr>
      <td><%= choice.option %></td>
      <td><%= question.responses.where("response = ?", choice.id).length %></td>
    </tr>

    <% end %>


  <% else %>

    <tr><td><h2><%= question.body %></h2></td></tr>

    <% question.responses.each do |response| %>
      <tr><td><%= response.response %></td></tr>
    <% end %>

  <% end %>


<% end %>
</table>

app/views/polls/update.html.erb
<h1>Polls#update</h1>
<p>Find me in app/views/polls/update.html.erb</p>

app/views/questions/_form.html.erb
<table class="table table-striped">

<%= form_for Question.new(:poll_id => @poll.id) do |f| %>
  <%= f.hidden_field :poll_id %>
  <div class="field">
    <tr><%= f.label 'Create A New Question:' %></tr>
    <tr><%= f.text_field :body, class: 'span5' %></tr>
  </div>

  <div class="actions">
    <tr><%= f.submit class: 'btn' %></tr>
  </div>
<% end %>
</table>

app/views/questions/_update_form.html.erb
<%= form.fields_for :questions do |question_form| %>
  <tr>
  <div class="field">
    <td><%= question_form.text_field :body %></td>
    <td><%= question_form.check_box :_destroy %></td>
  </div>
  </tr>
  <tr><td>
    Current Option Count: <%= question_form.object.choices.length %>  |
    <%= link_to "Manage Options", manage_choices_path(@poll.edit_key, question_form.object.id) %>


    </td><td></td></tr>
<% end %>

app/views/questions/manage_choices.html.erb
<h1><% @question.body %></h1>

<%= form_for @question, :url => question_path(@question) do |question_form| %>

 <%= render :partial => 'choices/update_form', :locals => {:form => question_form} %>

 <%= question_form.submit %>
<% end %>

  <%= render 'choices/form', :question => @question %>

  <%= link_to ' link back to poll', poll_edit_path(@question.poll.edit_key) %>